### ISSUE TITLE
User is unable to view board if not part of a GHE team

### ISSUE THREAD

**Issue by dlleigh** [waffleio/waffle.io-takeout#45]
At least 3 people in our group have experienced this:
   
1) After setting up Waffle for our GitHub Enterprise, a user logs in and authorizes Waffle to use their GHE identity
2) User tries to load a repo in Waffle and sees no issues.  User cannot add issues to the board
3) Add user to a team in GitHub
4) User reloads browser and can now see the board
5) If user is removed from the team in GitHub, they can still reload and see the board.

**Comment by homeyer** [comment]
Thanks for opening this. How critical is this for your team?

I'm assuming that user can't interact with cards, but they can view them, right?

**Comment by dlleigh** [comment]
No, they cannot view the cards either (empty board).  It's pretty critical
as it pretty much ruins the users' initial experience using the tool.

David Leigh
STSM, Project Whitewater
IBM Development Platform
dleigh@us.ibm.com, (919) 254-7129

Learn more about Project Whitewater:  http://www.newwayto.work

**Comment by homeyer** [comment]
Scheduling it into our current iteration.

**Comment by homeyer** [comment]
@dlleigh what version of GH:E do you have?

**Comment by dlleigh** [comment]
we are currently running v2.2.

**Comment by ashumz** [comment]
Hi @dlleigh -- 

I wanted to check in with you on this to clarify the issue. When users who are not added to a team try to access a board, what do they see? If a user has not been added to a team, they might not be able to view a repository due to permissions issues. Are you seeing unexpected behavior there? 

Or is your issue moreso around the fact that once users are added to a team and given repo access, when they are removed from a repository they still can see the repository in Waffle? We want to make sure we address your concern either way, but the first case might be expected given that GitHub Enterprise requires certain permissions to have access to repositories, and Waffle respects those same permissions at this point in time. 

Thanks for any clarification! 

Ashley

**Comment by dlleigh** [comment]
Hi.  When they try to access a board without being a member of a team, they see an empty board.   Regarding permissions, these repos are public in GitHub Enterprise, so there should not be a problem there.  Also, after removing the user from all teams they can still access the board, if they managed to access the board before being removed.

**Comment by homeyer** [comment]
reproduced and broken down into #117 and #118, in the current iteration.

**Comment by homeyer** [comment]
Fixed, going out with takeout version 2.2.2.
