### ISSUE TITLE
extend takeout licenses to 12/31 for existing users

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#65]

**Comment by homeyer** [comment]
also alert any customers whose licenses are extended.

**Comment by homeyer** [comment]
- [ ] Coinbase
- [ ] Polymer
- [ ] IBM
- [ ] ScotiaBank
- [ ] Action Pack Media
- [ ] Rackspace
- [ ] Fortna
- [ ] Walmart
- [ ] Yahoo
- [ ] Curse
- [ ] Ally
- [ ] Gistia
- [ ] Bloomberg
- [ ] Enova
- [ ] Schibsted
- [ ] Chartmogul
- [ ] Dell

**Comment by homeyer** [comment]
Note - not all of these were extensions (some were created before the 90 day limit was changed), so we should phrase the message as "your trial will expire at the end of the year", etc, vs revealing that it was extended by x days or whatnot.

**Comment by ashumz** [comment]
@homeyer How is this being handled? Is it an automated email or are we reaching out one by one? I think this would be a great opportunity to offer a check in as well, so might be nice to customize the content a bit beyond just a notice of new expiration date - let me know how I can help.

**Comment by ashumz** [comment]
also note that Polymer shouldn't get this since we offered the a free account for lifetime - but we should still check in. I really want a testimonial from them :)

**Comment by ashumz** [comment]
Everyone who has downloaded Takeout since Mixpanel was added 

CoreOS - brandon@ifup.org downloaded on Oct 14 
Target -  dan.cundiff@gmail.com downloaded on Oct 21
Maven Securities  - nmosafi@gmail.com downloaded on Oct 28
Polymer - compismyrx@gmail.com (Daniel Freedman) last downloaded on Oct 15 (we should set up a first download vs upgrade funnel) 
Cisco -  ahmeali@cisco.com (Ahmed Ali) last downloaded on Oct 16
Sony - don.j.olmstead@gmail.com last downloaded on Oct 15
Avalon Labs - Jacob Fike jacob@avalonlabs.net downloaded on Oct 14
 jonphill9@gmail.com downloaded on Oct 11

Accepted license, did not download
Compose.io - jonphill9@gmail.com accepted license on Oct 14, no download

**Comment by ashumz** [comment]
waiting on @homeyer to contact Walmart and Coinbase before closing this out.
